# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: #[push, pull_request]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildWindows:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hmm --quiet
          haxelib run hmm install --quiet
          haxelib list
        shell: cmd
      - name: Compile
        run: haxelib run lime build windows -D nightly
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: buildWindows
          path: export/release/windows/bin
